class FeedbackMailer < ApplicationMailer
  def send_feedback(feedback)
    @greeting = "This is a greeting"
    @body = 'This message was generated by a default template. To customize your message, look at app/mailers/feedback_mailer.rb'
    mail to: 'dschmura@humbledaisy.com', subject: @greeting, from: feedback.email, bcc: feedback.email
  end



  # Subject can be set in your I18n file at config/locales/en.yml
  # with the following lookup:
  #
  #   en.feedback_mailer.RAILS_ENV=development.subject
  #
  def RAILS_ENV=development
    @greeting = "Hi"

    mail to: "to@example.org"
  end
end
