default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: whackahole_development

test:
  <<: *default
  database: whackahole_test

staging:
  <<: *default
  database: whackahole_staging
  username: <%= Rails.application.credentials.STAGING_DB_USERNAME %>
  password: <%= Rails.application.credentials.STAGING_DB_PASSWORD %>

production:
  <<: *default
  database: whackahole_production
  username: <%= Rails.application.credentials.PRODUCTION_DB_USERNAME %>
  password: <%= Rails.application.credentials.PRODUCTION_DB_PASSWORD %>

